version: '3.2'

services:
  db:
    image: postgres:15
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - scm_data:/var/lib/postgresql/scm/data

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'

    volumes:
      - .:/app/backend

  backend:
    build: .
    ports:
      - '8000:8000'

    depends_on:
      - frontend
      - db

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - .:/app/backend

volumes:
  scm_data: