version: '3.2'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - cms_data:/var/lib/postgresql/cms/data

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'

    volumes:
      - .:/app/backend

  backend:
    build: .
    ports:
      - '8000:8000'

    depends_on:
      - frontend
      - db

    volumes:
      - .:/app/backend

volumes:
  cms_data: